### ISSUE TITLE
Format the json file properly so that each movie will have all details in a proper way

### ISSUE THREAD

**Issue by hkiiita** [hkbiet/Python#3]
#3  ## the json file properly so that each movie will have all details in a proper way.
The JSON apparently needs to formatted using movie names as keys ; hence the actual CSV format needs to be preserved.
https://github.com/opencodeiiita/Monty_Python_Class/pull/47#issuecomment-576268214

**Comment by sandipan-basak** [comment]
Hi, I am new to open-source. Can I work on this issue if no one else is working on this currently?

**Comment by VanSr** [comment]
Is this the output you are looking for?
[result.json](https://drive.google.com/file/d/1wb1_1hv4Mn9Mku9KKeQZKbdLPdw7KfOp/view?usp=sharing)
I have the file ready to push, but I need permission.

**Comment by NovusEdge** [comment]
Hi There!
 Can I work on this?, I'm new to open-source.

**Comment by hkbiet** [comment]
> 
> 
> Is this the output you are looking for?
> [result.json](https://drive.google.com/file/d/1wb1_1hv4Mn9Mku9KKeQZKbdLPdw7KfOp/view?usp=sharing)
> I have the file ready to push, but I need permission.

Yes please !

**Comment by hkiiita** [comment]
> 
> 
> Hi There!
> Can I work on this?, I'm new to open-source.

Yes please !

**Comment by hkbiet** [comment]
@VanSr @NovusEdge  Anyone amongst you who pings here first shall be allowed to work on this.
